### ISSUE TITLE
TAGS Link (upper left) not going to right place.

### ISSUE THREAD

**Issue by jduckles** [tags/geologgerui#3]
Clicking the TAGS logo takes you to the root of static.cybercommons.org, should probably point to the app itself.
![image](https://f.cloud.github.com/assets/119403/894061/717c0dfe-fab3-11e2-9ce0-fe459dadc76a.png)

**Comment by phildow** [comment]
This is due to weirdness with the root directory. Can you do virtual root directories on the server? So that / points to /apptest/geologger/ for files in that directory? Makes aligning the development environment with the deployment environment difficult as well.

Luckily our app is small and all the html is in one directory, so I'm just going to have it point at index.html

**Comment by jduckles** [comment]
The way things are set up on the new server this is no longer a problem.
